version: '3.6'
services:
  api:
    build: .
    volumes:
      - ./:/src/app
    depends_on:
      - mysql
    ports:
      - 3001:3000
    networks:
      defaultNetwork:
        ipv4_address: 10.5.0.5

  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - api
    networks:
      defaultNetwork:
        ipv4_address: 10.5.0.6
  
  mysql:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE='school'
      - MYSQL_PASSWORD='123456'
      - MYSQL_USER='rodrigo'
      - MYSQL_ROOT_PASSWORD='123456'
      - MYSQL_ROOT_HOST='%'
    volumes:
      - db:/var/lib/mysql
    networks:
      defaultNetwork:
        ipv4_address: 10.5.0.4

volumes:
  db:

networks:
  defaultNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: "10.5.0.0/24"
          gateway: "10.5.0.1"