version: '3.6'
services:
  api:
    build: 
      context: ./src/docker
      dockerfile: dockerfile
    volumes:
      - ./:/srv/app
    depends_on:
      - mysql
    ports:
      - 3001:3000

  nginx:
    image: nginx
    ports:
      - 8080:80
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - api
  
  mysql:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE='school'
      - MYSQL_PASSWORD='123456'
      - MYSQL_USER='rodrigo'
      - MYSQL_ROOT_PASSWORD='123456'
      - MYSQL_ROOT_HOST='%'
    volumes:
      - db:/var/lib/mysql

volumes:
  db: