name: Push to EC2
on:
  push:
    branches:
      - master

jobs:

  build:
    name: Deploy AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Copy file with SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.AWS_PRIVATE_KEY}}
          SOURCE: "./"
          REMOTE_HOST: ${{secrets.HOSTNAME}}
          REMOTE_USER: ${{secrets.USER_NAME}}
          TARGET: ${{secrets.PATH_TARGET}}
          
      - name: executing remote ssh commands using key pair
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME  }}
          key: ${{ secrets.AWS_PRIVATE_KEY  }}
          username: ${{ secrets.USER_NAME  }}
          port: 22
          script: |
              #logged in ec2.
              cd app/api-school
              git pull
              docker-compose up --force-recreate --build -d